const machineWithoutRutineData = {
  lastSeason: '2021-01-01',
  weight: { mainWeight: 5, extraWeight: 0 },
  series: 1,
  repetitions: 15,
  restTime: 30,
  feedback: 'Mantener peso',
};

export const machinesMock = [
  {
    id: 1,
    exercise: 'press de pecho',
    image: {
      primary: 'assets/machines/pressPecho.png',
      secondary: 'assets/machines/pressPecho2.png',
    },
    machineType: 'black',
    muscularGroup: 'chest',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 2,
    exercise: 'remo',
    image: {
      primary: 'assets/machines/remo.png',
      secondary: 'assets/machines/remo2.png',
    },
    machineType: 'black',
    muscularGroup: 'back',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 3,
    exercise: 'biceps',
    image: {
      primary: 'assets/machines/bicepsWhite.png',
      secondary: 'assets/machines/bicepsWhite2.png',
    },
    machineType: 'white',
    muscularGroup: 'biceps',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 4,
    exercise: 'estirar hacia abajo',
    image: {
      primary: 'assets/machines/tirarAbajo.png',
      secondary: 'assets/machines/tirarAbajo2.png',
    },
    machineType: 'black',
    muscularGroup: 'back',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 5,
    exercise: 'press de tríceps',
    image: {
      primary: 'assets/machines/triceps.png',
      secondary: 'assets/machines/triceps2.png',
    },
    machineType: 'black',
    muscularGroup: 'triceps',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 6,
    exercise: 'extensión de pantorrilla',
    image: {
      primary: 'assets/machines/pantorrilla.png',
      secondary: 'assets/machines/pantorrilla2.png',
    },
    machineType: 'black',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 7,
    exercise: 'elevación lateral',
    image: {
      primary: 'assets/machines/levaciónLateral.png',
      secondary: 'assets/machines/pantorrilla2.png',
    },
    machineType: 'black',
    muscularGroup: 'shoulders',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 8,
    exercise: 'mariposa',
    image: {
      primary: 'assets/machines/mariposa.png',
      secondary: 'assets/machines/mariposa2.png',
    },
    machineType: 'black',
    muscularGroup: 'chest',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 9,
    exercise: 'press de pierna sentado',
    image: {
      primary: 'assets/machines/pressPiernaSentado.png',
      secondary: 'assets/machines/pressPiernaSentado2.png',
    },
    machineType: 'black',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 10,
    exercise: 'contracción bíceps',
    image: {
      primary: 'assets/machines/contraccionBiceps.png',
      secondary: 'assets/machines/contraccionBiceps2.png',
    },
    machineType: 'black',
    muscularGroup: 'biceps',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 11,
    exercise: 'glúteos',
    image: {
      primary: 'assets/machines/gluteo.png',
      secondary: 'assets/machines/gluteo2.png',
    },
    machineType: 'black',
    muscularGroup: 'glutes',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 12,
    exercise: 'aducción de caderas',
    image: {
      primary: 'assets/machines/aduccionCaderas.png',
      secondary: 'assets/machines/aduccionCaderas2.png',
    },
    machineType: 'black',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 13,
    exercise: 'extensora de hombros',
    image: {
      primary: 'assets/machines/extensoraHombros.png',
      secondary: 'assets/machines/extensoraHombros2.png',
    },
    machineType: 'black',
    muscularGroup: 'shoulders',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 14,
    exercise: 'contracción de piernas',
    image: {
      primary: 'assets/machines/contraccionPiernas.png',
      secondary: 'assets/machines/contraccionPiernas2.png',
    },
    machineType: 'black',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 15,
    exercise: 'contracción de piernas sentado',
    image: {
      primary: 'assets/machines/contraccionPiernasSentado.png',
      secondary: 'assets/machines/contraccionPiernasSentado2.png',
    },
    machineType: 'black',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 16,
    exercise: 'extensión de pierna',
    image: {
      primary: 'assets/machines/extensionPierna.png',
      secondary: 'assets/machines/extensionPierna2.png',
    },
    machineType: 'black',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 17,
    exercise: 'abducción de caderas',
    image: {
      primary: 'assets/machines/abduccionCaderas.png',
      secondary: 'assets/machines/abduccionCaderas2.png',
    },
    machineType: 'black',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 18,
    exercise: 'abdominales',
    image: {
      primary: 'assets/machines/abdominalesWhite.png',
      secondary: 'assets/machines/abdominalesWhite2.png',
    },
    machineType: 'white',
    muscularGroup: 'abs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 19,
    exercise: 'contracción de piernas sentado',
    image: {
      primary: 'assets/machines/contraccionPiernasSentadoWhite.png',
      secondary: 'assets/machines/contraccionPiernasSentadoWhite2.png',
    },
    machineType: 'white',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 20,
    exercise: 'estirar hacía abajo',
    image: {
      primary: 'assets/machines/tirarAbajoWhite.png',
      secondary: 'assets/machines/tirarAbajoWhite2.png',
    },
    machineType: 'white',
    muscularGroup: 'back',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 21,
    exercise: 'press de pecho',
    muscularGroup: 'chest',
    image: {
      primary: 'assets/machines/pressPechoWhite.png',
      secondary: 'assets/machines/pressPechoWhite2.png',
    },
    machineType: 'white',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 22,
    exercise: 'press de hombros',
    muscularGroup: 'shoulders',
    image: {
      primary: 'assets/machines/pressHombroswhite.png',
      secondary: 'assets/machines/pressHombroswhite2.png',
    },
    machineType: 'white',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 23,
    exercise: 'press de triceps',
    image: {
      primary: 'assets/machines/pressTricepsWhite.png',
      secondary: 'assets/machines/pressTricepsWhite2.png',
    },
    machineType: 'white',
    muscularGroup: 'triceps',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 24,
    exercise: 'squats',
    image: {
      primary: 'assets/machines/squatsWhite.png',
      secondary: 'assets/machines/squatsWhite2.png',
    },
    machineType: 'white',
    muscularGroup: 'legs',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
  {
    id: 25,
    exercise: 'remo con cable',
    image: {
      primary: 'assets/machines/remoCableWhite.png',
      secondary: 'assets/machines/remoCableWhite2.png',
    },
    machineType: 'white',
    muscularGroup: 'back',
    everDone: false,
    machineRutineData: { ...machineWithoutRutineData },
  },
];
