const machineWithoutRutineData = {
  lastSeason: '2021-01-01',
  weight: { mainWeight: 5, extraWeight: 0 },
  series: 1,
  repetitions: 15,
  restTime: 30,
  feedback: 'Mantener peso',
};

export const machinesMock = [
  {
    id: 1,
    exercise: 'press de pecho',
    image: {
      primary: 'assets/machines/pressPecho.png',
      secondary: 'assets/machines/pressPecho2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 5, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 2,
    exercise: 'remo',
    image: {
      primary: 'assets/machines/remo.png',
      secondary: 'assets/machines/remo2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 5, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 3,
    exercise: 'biceps',
    image: {
      primary: 'assets/machines/bicepsWhite.png',
      secondary: 'assets/machines/bicepsWhite2.png',
    },
    machineType: 'white',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 4,
    exercise: 'estirar hacía abajo',
    image: {
      primary: 'assets/machines/tirarAbajo.png',
      secondary: 'assets/machines/tirarAbajo2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 5,
    exercise: 'press de tríceps',
    image: {
      primary: 'assets/machines/triceps.png',
      secondary: 'assets/machines/triceps2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 6,
    exercise: 'extensión de pantorrilla',
    image: {
      primary: 'assets/machines/pantorrilla.png',
      secondary: 'assets/machines/pantorrilla2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 7,
    exercise: 'elevación lateral',
    image: {
      primary: 'assets/machines/levaciónLateral.png',
      secondary: 'assets/machines/pantorrilla2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 8,
    exercise: 'mariposa',
    image: {
      primary: 'assets/machines/mariposa.png',
      secondary: 'assets/machines/mariposa2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 9,
    exercise: 'press de pierna sentado',
    image: {
      primary: 'assets/machines/pressPiernaSentado.png',
      secondary: 'assets/machines/pressPiernaSentado2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 10,
    exercise: 'contracción biceps',
    image: {
      primary: 'assets/machines/contraccionBiceps.png',
      secondary: 'assets/machines/contraccionBiceps2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 11,
    exercise: 'gluteos',
    image: {
      primary: 'assets/machines/gluteo.png',
      secondary: 'assets/machines/gluteo2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 12,
    exercise: 'aducción de caderas',
    image: {
      primary: 'assets/machines/aduccionCaderas.png',
      secondary: 'assets/machines/aduccionCaderas2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 13,
    exercise: 'extensora de hombros',
    image: {
      primary: 'assets/machines/extensoraHombros.png',
      secondary: 'assets/machines/extensoraHombros2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 14,
    exercise: 'contracción de piernas',
    image: {
      primary: 'assets/machines/contraccionPiernas.png',
      secondary: 'assets/machines/contraccionPiernas2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 15,
    exercise: 'contracción de piernas sentado',
    image: {
      primary: 'assets/machines/contraccionPiernasSentado.png',
      secondary: 'assets/machines/contraccionPiernasSentado2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 16,
    exercise: 'extension de pierna',
    image: {
      primary: 'assets/machines/extensionPierna.png',
      secondary: 'assets/machines/extensionPierna2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
  {
    id: 17,
    exercise: 'abducción de caderas',
    image: {
      primary: 'assets/machines/abduccionCaderas.png',
      secondary: 'assets/machines/abduccionCaderas2.png',
    },
    machineType: 'black',
    everDone: false,
    machineRutineData: {
      lastSeason: '2021-01-01',
      weight: { mainWeight: 1, extraWeight: 0 },
      series: 1,
      repetitions: 15,
      restTime: 30,
      feedback: 'Mantener peso',
    },
  },
];
